alias sc='script/console'
alias sg='script/generate'
alias sd='script/destroy'
alias migrate='rake db:migrate db:test:clone'
alias befs='bundle exec foreman start -f Procfile.dev'
alias taildev='tail -f log/development.log'
